# Generated by Django 3.1.4 on 2020-12-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alog', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='create_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='modify_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
