# Generated by Django 3.1.4 on 2020-12-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alog', '0006_auto_20201218_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='create_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
